# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/beatscore',
                'doc_host': 'https://funkstop.github.io',
                'git_url': 'https://github.com/funkstop/beatscore',
                'lib_path': 'beatscore'},
  'syms': { 'beatscore.beatscore': {},
            'beatscore.core': {'beatscore.core.foo': ('core.html#foo', 'beatscore/core.py')},
            'beatscore.test': {}}}
